version: '3.8'

services:
  db:
    container_name: todos-db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  backend:
    container_name: todos-backend
    image: nabiluddin01/todos-backend
    build:
      context: ./backend
      args:
        - DATABASE_URL=postgresql://todosdbuser:v12rjAXsbupq4s8EpmUBukay2tBgWKoK@dpg-cus8thqn91rc73djgmb0-a.singapore-postgres.render.com/todosdb_zj0v?schema=todos
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://todosdbuser:v12rjAXsbupq4s8EpmUBukay2tBgWKoK@dpg-cus8thqn91rc73djgmb0-a.singapore-postgres.render.com/todosdb_zj0v?schema=todos
      - CORS_ORIGINS=https://todos-frontend-vjth.onrender.com
      - APP_PORT=5000
      - JWT_SECRET=0318292c25b02f03f54b83bb81867a727c81b2ba391b50a675d72a89e56babfe9f96007d5f1b1a03a10a607c552edf7d5381db8c52a829136a965389c1074e13222ae08d5ae455d216ff2d2cb5ee79258f6953e8e04cddc85986eb6793828de0d8b4da87294d79800e5ca1d88ae19e69609bdca287045818d2f7248e3fde668fe8b9718870b98cdc580534a5fbe0c5de78237057376bb9b59ef6efda49e60a0c633ad0c81edf4dfa25a0a7871643f012bc7552676fe846ffa40e919d9982a8da72caef8eaefd096af987d835bb783c738ee37a516508844af55eebc572d7db17c22af269fc06bb4f47ad250552446dd263193173cd01f7b77964f5b5fa50480e

  frontend:
    container_name: todos-frontend
    image: nabiluddin01/todos-frontend
    build: ./todo-list
    ports:
      - 3000:80
    environment:
      - VITE_BACKEND_API=https://todos-backend-p5af.onrender.com
      - VITE_ENCRYPTION_KEY=wJ#8vG$P@Xn2Z3k5!Q7rU9t%L4pMfNhVxCjA*Yd&Bq6KsET
      - VITE_SESSION_DURATION=86400

volumes:
  postgres-data:
